### ISSUE TITLE
The link of "here" is inaccessible!       

### ISSUE THREAD

**Issue by lst1975** [vmware/ml-ops-platform-for-vsphere#27]
### Describe the bug

Documentation/Getting Started/Setup Authentication/Option 2: Use Embedded Dex with upstream OIDC
[Prerequisites] A Tanzu Kubernetes Cluster with Kubeflow on vSp[here](http://localhost:1313/ml-ops-platform-for-vsphere/main/docs/deployment/carvel/) deployed. If you haven’t, please follow the tutorial **here**.

### Reproduction steps

![image](https://user-images.githubusercontent.com/28725147/212489674-46d81d33-8168-4730-8afe-66dadc8a7714.png)

### Expected behavior

accessible

**Comment by jojo8b** [comment]
The link is referring to localhost like is: http://localhost:1313/ml-ops-platform-for-vsphere/main/docs/deployment/carvel/
A domain name/IP which is accessible to the general public is required.
