### ISSUE TITLE
"would be build as" ---> would be built as

### ISSUE THREAD

**Issue by lst1975** [vmware/ml-ops-platform-for-vsphere#30]
### Describe the bug

There are two main tasks: train and evaluation. Each would be "build" as a pipeline component later

### Reproduction steps

There are two main tasks: train and evaluation. Each would be built as a pipeline component later

### Expected behavior

There are two main tasks: train and evaluation. Each would be **built** as a pipeline component later

**Comment by jojo8b** [comment]
please provide the doc location of this error. For example,  Documentation / Getting Started / Prerequisites.

**Comment by lst1975** [comment]
换个表达？to share和to provide要并列一致，换成and。用确认无误的表达？



---Original---
From: ***@***.***&gt;
Date: Wed, Jan 18, 2023 16:33 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [vmware/ml-ops-platform-for-vsphere] "would be build as" ---&gt;would be built as (Issue #30)




 
please provide the doc location of this error. For example,  Documentation / Getting Started / Prerequisites.

**Comment by jojo8b** [comment]
Documentation / Basic Guides / Pipeline
