### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by lst1975** [vmware/ml-ops-platform-for-vsphere#35]
### Describe the bug

An **inteagrated** [VMware vSphere](https://www.vmware.com/products/vsphere.html#resources), Bitfusion delivers the ability to share resources in addition to **providing** better utilization of existing or new hardware accelerator resources.

### Reproduction steps

An **integrated** [VMware vSphere](https://www.vmware.com/products/vsphere.html#resources), Bitfusion delivers the ability to share resources in addition to **provide** better utilization of existing or new hardware accelerator resources.

### Expected behavior

An **integrated** [VMware vSphere](https://www.vmware.com/products/vsphere.html#resources), Bitfusion delivers the ability to share resources in addition to **provide** better utilization of existing or new hardware accelerator resources.

**Comment by jojo8b** [comment]
in addition to 的中文意思為「除了...之外」，要注意此處的 to 是作為介係詞，因此後面要加上名詞或動名詞。

用法：in addition to N/V-ing

**Comment by lst1975** [comment]
let me go。经常这样用。建议用谷歌翻译试一下。我现在无法上网，不知道#35是哪个



---Original---
From: ***@***.***&gt;
Date: Wed, Jan 18, 2023 16:21 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [vmware/ml-ops-platform-for-vsphere] Syntax error (Issue #35)




 
in addition to 的中文意思為「除了...之外」，要注意此處的 to 是作為介係詞，因此後面要加上名詞或動名詞。
 
用法：in addition to N/V-ing

**Comment by lst1975** [comment]
ok



---Original---
From: ***@***.***&gt;
Date: Thu, Mar 9, 2023 21:37 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [vmware/ml-ops-platform-for-vsphere] Syntax error (Issue #35)




 
Double checked. "ing" may be better.

**Comment by lst1975** [comment]
I mean that we use "to do xxx and to provide xxx", do not use the clause of "in addition to", because I am not sure about it.



---Original---
From: ***@***.***&gt;
Date: Thu, Mar 9, 2023 21:37 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [vmware/ml-ops-platform-for-vsphere] Syntax error (Issue #35)




 
Double checked. "ing" may be better.
