### ISSUE TITLE
In the sentence of "But we will build a Bitfusion Kernel in the near feature", what is the meaning of "near feature"?      

### ISSUE THREAD

**Issue by lst1975** [vmware/ml-ops-platform-for-vsphere#40]
### Describe the bug

What is the meaning of "near feature"?
Documentation/Advanced Features/Bitfusion/Roadmap.

### Reproduction steps

What is the meaning of "near feature"?

### Expected behavior

What is the meaning of "near feature"?

**Comment by arielzhu0512** [comment]
Discussion with corresponding lead is required.
